#!/bin/bash

# Download Lenna.png
wget https://upload.wikimedia.org/wikipedia/en/2/24/Lenna.png

# Convert to edge detected version
convert Lenna.png -charcoal 1 Edge.png

# Download prerequisites
git clone https://github.com/richelbilderbeek/AsciiArter
git clone https://github.com/richelbilderbeek/DotMatrix
git clone https://github.com/richelbilderbeek/RibiClasses
git clone https://github.com/richelbilderbeek/RibiLibraries

# Build AsciiArter
cd AsciiArter
qmake AsciiArterConsole.pro
make debug
cp AsciiArterConsole ../
cd ..

# Convert Edge to Ascii Arter
AsciiArterConsole Edge.png art.txt 78

# Show art as text
cat art.txt

# Show art by cowsay
cat art.txt | cowsay

# Create cowfile
echo "$the_cow = <<\"EOC\";" > art.cow
echo "  $thoughts" >> art.cow
echo "   $thoughts >> art.cow
cat art.txt >> artc.ow
echo "EOC" >> art.cow

# Show cowfile
cowsay -f ./art.cow "Hello"